### ISSUE TITLE
Configure Role-Based Permissions for Database Tables

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/backend-SafeTrust#84]
## Issue Summary
Configure basic role-based permissions for all database tables by creating dedicated YAML files in the metadata directory, granting full access to both tenant and landlord roles. This simplifies our authorization approach by relying on Firebase JWT claims for role designation. Please check this previous [PR](https://github.com/safetrustcr/Backend/pull/40), where we already added authentication to the users table. We need to do the same for the rest of the tables.

## Type of Issue
- [x] Feature Request
- [ ] Bug
- [x] Security
- [ ] Documentation
- [ ] Other

## Current Behavior
Tables currently lack defined permissions and dedicated metadata files. Our authorization system needs to be configured to work with the role information that will be provided by Firebase JWT claims.

## Expected Behavior
Each table should have its own metadata file in the proper directory structure, allowing full access to both tenant and landlord roles, with roles being determined by Firebase JWT claims. This will create a foundation for our authorization system that we can later refine based on specific access requirements.

## Implementation Steps

1. Create separate permission files for each table in the metadata directory:

For apartments table:
```yaml
# metadata/databases/safetrust/tables/public_apartments.yaml
table:
  name: apartments
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

For apartment_images table:
```yaml
# metadata/databases/safetrust/tables/public_apartment_images.yaml
table:
  name: apartment_images
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

For bid_requests table:
```yaml
# metadata/databases/safetrust/tables/public_bid_requests.yaml
table:
  name: bid_requests
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

For bid_status_histories table:
```yaml
# metadata/databases/safetrust/tables/public_bid_status_histories.yaml
table:
  name: bid_status_histories
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

For escrow_transactions table:
```yaml
# metadata/databases/safetrust/tables/public_escrow_transactions.yaml
table:
  name: escrow_transactions
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

For escrow_xdr_transactions table:
```yaml
# metadata/databases/safetrust/tables/public_escrow_xdr_transactions.yaml
table:
  name: escrow_xdr_transactions
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

For escrow_api_calls table:
```yaml
# metadata/databases/safetrust/tables/public_escrow_api_calls.yaml
table:
  name: escrow_api_calls
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

For apartment_contracts table:
```yaml
# metadata/databases/safetrust/tables/public_apartment_contracts.yaml
table:
  name: apartment_contracts
  schema: public
select_permissions:
  - role: tenant
    permission:
      columns: "*"
      filter: {}
  - role: landlord
    permission:
      columns: "*"
      filter: {}
```

2. Update JWT claims mapping:
```yaml
HASURA_GRAPHQL_JWT_SECRET: {
  "type": "RS256",
  "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
  "claims_map": {
    "x-hasura-allowed-roles": {
      "path": "$.roles"
    },
    "x-hasura-default-role": {
      "path": "$.role"
    },
    "x-hasura-user-id": {
      "path": "$.user_id"
    }
  }
}
```

## Environment Details
- Project Version: v1.0.0
- Hasura Version: v2.42.0
- PostgreSQL: 15-3.3

### Expected JWT Structure
```json
{
  "user_id": "firebase-user-id",
  "role": "tenant",  // or "landlord"
  "roles": ["tenant"]  // or ["landlord"]
}
```

### Tables Requiring Permission Updates
- apartments
- apartment_images
- bid_requests
- bid_status_histories
- escrow_transactions
- escrow_xdr_transactions
- escrow_api_calls
- apartment_contracts

Also you can reference this [tutorial](https://hasura.io/blog/authentication-and-authorization-using-hasura-and-firebase) as a base.
