### ISSUE TITLE
CI/CD Pipeline Implementation on Backend Issue

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/backend-SafeTrust#94]
Issue Summary
Design and implement a comprehensive CI/CD pipeline for SafeTrust backend platform, incorporating automated Karate testing, security scanning, and multi-environment deployments with rollback capabilities.

Type of Issue
[x] Feature Request
[ ] Bug
[ ] Documentation
[ ] Performance
[ ] Security
[ ] Other

Current Behavior
Currently, deployments are manual with no automated testing or deployment pipeline in place. This results in:
- Inconsistent deployment processes
- Manual security checks
- No automated Karate test execution
- Lack of standardized environment configurations
- No automated rollback mechanism

Expected Behavior
A fully automated CI/CD pipeline with the following stages and features:

1. Code Quality & Testing Stage
```yaml
quality_checks:
  stages:
    - lint:
        tools:
          - eslint
        config: .eslintrc.json
    - static_analysis:
        tools:
          - SonarQube
        metrics:
          - code_coverage: >= 80%
          - code_smells: 0
          - duplications: < 3%
    - functional_tests:
        framework: Karate
        config: /app/tests/karate/features
        reports:
          - cucumber-html-reporter
        parallel_execution: true
```

2. Security Scanning Stage
```yaml
security_checks:
  stages:
    - dependency_scan:
        tools:
          - npm audit
          - Snyk
        severity_threshold: medium
    - rate_limit_check:
        tools:
          - custom_scanner
        verify:
          - express-rate-limit configuration
    - secrets_scan:
        tools:
          - GitGuardian
          - TruffleHog
    - env_check:
        verify:
          - dotenv configuration
          - sensitive variables
```

3. Build & Artifact Stage
```yaml
build_process:
  stages:
    - npm_install:
        production: true
        ci: true
    - docker_build:
        base_image: node:18-alpine
        multi_stage: true
        copy:
          - package*.json
          - /app/tests/karate.jar
          - /app/tests/karate/features
    - artifact_creation:
        type: docker_image
    - artifact_signing:
        tool: Cosign
```

4. Deployment Stages
```yaml
deployment:
  environments:
    dev:
      trigger: on_commit
      branch: develop
      auto_deploy: true
      env_vars:
        - NODE_ENV=development
    staging:
      trigger: manual
      branch: release/*
      approval_required: true
      env_vars:
        - NODE_ENV=staging
    production:
      trigger: manual
      branch: main
      approval_required: true
      rollback_enabled: true
      env_vars:
        - NODE_ENV=production
```

5. Post-Deployment Stage
```yaml
post_deployment:
  stages:
    - smoke_tests:
        timeout: 5m
        retry_count: 3
        verify:
          - express server health
          - nodemailer configuration
    - logging_check:
        tool: winston
        verify:
          - log generation
          - log levels
    - monitoring:
        tools:
          - Prometheus
          - Grafana
    - alerting:
        channels:
          - Slack
          - Email
```

Environment Details
- Project Version: v1.0.0
- CI/CD Platform: GitLab CI/CD or GitHub Actions
- Container Registry: AWS ECR
- Node.js Version: 18.x
- Java Version: 11+ (for Karate tests)

Pipeline Configuration Example
```yaml
stages:
  - validate
  - test
  - build
  - security
  - deploy
  - post-deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

.npm_install: &npm_install
  before_script:
    - npm ci --cache .npm --prefer-offline

validate:
  <<: *npm_install
  script:
    - npm run lint

test:
  image: adoptopenjdk/openjdk11
  script:
    - npm test
  artifacts:
    reports:
      junit: karate-reports/*.xml
```

Rollback Strategy
```yaml
rollback:
  triggers:
    - health_check_failure
    - error_rate_threshold: > 1%
    - latency_threshold: > 500ms
  process:
    - stop_incoming_traffic
    - revert_deployment
    - verify_express_server
    - verify_rate_limits
    - resume_traffic
  notification:
    channels:
      - slack
      - email (via nodemailer)
```

The key changes made to align with the package.json are:
1. Updated testing framework to Karate instead of Jest/Cypress
2. Added Java requirements for Karate test execution
3. Included express-rate-limit security checks
4. Added nodemailer configuration verification
5. Incorporated winston logging checks
6. Removed frontend-specific configurations
7. Updated notification system to use the existing nodemailer setup

### Make sure to follow the Git Guidelines for Atomic Commits and read Contributing Guide
The Pull request needs to have the format mentioned below in the Git Guideline

- [Contributing Guide ](https://github.com/safetrustcr/Frontend/issues/34)
- [Git Guidelines](https://github.com/safetrustcr/Frontend/issues/35)

If you apply to this issue with comments like:
"Can I get assigned?"
"Can I work on this?"

🙅‍♂️ You will not be assigned 🙅‍♀️

We value quality over speed. To be considered, explain in detail how you plan to resolve the issue. Thank you for understanding.
